Models/CoreValueRecognitions.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Team8_MVCApplication.Models
{
    public class CoreValueRecognitions
    {
        public int ID { get; set; }

        [Display(Name = "Recognition given to")]
        public Guid recognized { get; set; }

        [Display(Name = "Recognition given by")]
        public Guid recognizor { get; set; }

        [Display(Name = "Core Centric Value")]
        public CoreValue award { get; set; }

        [Display(Name = "Date Recognition is Given")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime recognizationDate { get; set; }

        public string Comments { get; set; }
        public enum CoreValue
        {
            Excellence = 1,
            Integrity = 2,
            Stewardship = 3,
            Accepting = 4,
            Innovative = 5,
            Balance = 6,
            Passion = 7

        }

        [ForeignKey("recognized")]
        public virtual Profile personRecognized { get; set; }

        [ForeignKey("recognizor")]
        public virtual Profile personRecognizor { get; set; }
    }
}

Controllers/CoreValueRecognitionsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Reactive;
using System.Web;
using System.Web.Mvc;
using Team8_MVCApplication.DAL;
using Team8_MVCApplication.Models;

namespace Team8_MVCApplication.Controllers
{
    public class CoreValueRecognitionsController : Controller
    {
        private Team8_MVCApplication_Context db = new Team8_MVCApplication_Context();

        // GET: CoreValueRecognitions
        public ActionResult Index()
        {
            var coreValueRecognitions = db.CoreValueRecognitions.Include(c => c.personRecognized).Include(c => c.personRecognizor);
            return View(coreValueRecognitions.ToList());
        }

        // GET: CoreValueRecognitions/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CoreValueRecognitions coreValueRecognitions = db.CoreValueRecognitions.Find(id);
            if (coreValueRecognitions == null)
            {
                return HttpNotFound();
            }
            return View(coreValueRecognitions);
        }

        // GET: CoreValueRecognitions/Create
        [Authorize]
        public ActionResult Create()
        {
            SelectList members = new SelectList(db.Profiles, "ProfileId", "fullName");
            string memberID = User.Identity.GetUserId();
            members = new SelectList(members.Where(x => x.Value != memberID).ToList(), "Value", "Text");
            ViewBag.recognized = members;
            return View();
        }

        // POST: CoreValueRecognitions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,recognized,recognizor,award,recognizationDate,Comments")] CoreValueRecognitions coreValueRecognitions)
        {
            if (ModelState.IsValid)
            {

                Guid memberID;
                Guid.TryParse(User.Identity.GetUserId(), out memberID);
                coreValueRecognitions.recognizor = memberID;
                db.CoreValueRecognitions.Add(coreValueRecognitions);
                db.SaveChanges();
                var recognizor = db.Profiles.Find(coreValueRecognitions.recognizor);
                var profile = db.Profiles.Find(coreValueRecognitions.recognized);
                var firstName = profile.profileFirstName;
                var lastName = profile.profileLastName;
                var fullNameRecognizor = recognizor.fullName;
                var email = profile.email;
                var msg = "Hi " + firstName + " " + lastName + ",\n\nWe wanted to notify you that your colleague, " + fullNameRecognizor + ", has recently given you a recognition.";
                msg += "\n\nTo access the recognition, please log into our system!";
                msg += "\n\nSincerely\nTeam 8";
                //notification += "<br/>" + firstName + " " + lastName + " at " + email;
                MailMessage myMessage = new MailMessage();
                MailAddress from = new MailAddress("nnjstull@gmail.com", "SysAdmin");
                myMessage.From = from;
                myMessage.To.Add(email);
                myMessage.Subject = "Recent recognition";
                myMessage.Body = msg;
                try
                {
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.UseDefaultCredentials = false;
                    smtp.Credentials = new System.Net.NetworkCredential("nnjstull@gmail.com", "An7igua@2095");
                    smtp.EnableSsl = true;
                    //smtp.Send(myMessage);
                    TempData["mailError"] = msg;
                    return View("mailError");
                }
                catch (Exception ex)
                {

                    TempData["mailError"] = ex.Message;
                    return View("mailError");
                }

                //return RedirectToAction("Index");
            }

            ViewBag.recognized = new SelectList(db.Profiles, "ProfileId", "fullName", coreValueRecognitions.recognized);
  
            return View(coreValueRecognitions);
        }

        // GET: CoreValueRecognitions/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CoreValueRecognitions coreValueRecognitions = db.CoreValueRecognitions.Find(id);
            if (coreValueRecognitions == null)
            {
                return HttpNotFound();
            }
           
            ViewBag.recognized = new SelectList(db.Profiles, "ProfileId", "fullName", coreValueRecognitions.recognized);
            ViewBag.recognizor = new SelectList(db.Profiles, "ProfileId", "fullName", coreValueRecognitions.recognizor);
            return View(coreValueRecognitions);
        }

        // POST: CoreValueRecognitions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,recognized,recognizor,award,recognizationDate,Comments")] CoreValueRecognitions coreValueRecognitions)
        {
            if (ModelState.IsValid)
            {
                db.Entry(coreValueRecognitions).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.recognized = new SelectList(db.Profiles, "ProfileId", "profileFirstName", coreValueRecognitions.recognized);
            ViewBag.recognizor = new SelectList(db.Profiles, "ProfileId", "profileFirstName", coreValueRecognitions.recognizor);
            return View(coreValueRecognitions);
        }

        // GET: CoreValueRecognitions/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CoreValueRecognitions coreValueRecognitions = db.CoreValueRecognitions.Find(id);
            if (coreValueRecognitions == null)
            {
                return HttpNotFound();
            }
            return View(coreValueRecognitions);
        }

        // POST: CoreValueRecognitions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CoreValueRecognitions coreValueRecognitions = db.CoreValueRecognitions.Find(id);
            db.CoreValueRecognitions.Remove(coreValueRecognitions);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/CoreValueRecognitions/Create.cshtml
@model Team8_MVCApplication.Models.CoreValueRecognitions

@{
    ViewBag.Title = "Create";
}

<h2>Centric Recognitions</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create Here!</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.recognized, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("recognized", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.recognized, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.recognizor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("recognizor", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.recognizor, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.award, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.award, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.award, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.recognizationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.recognizationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.recognizationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/CoreValueRecognitions/Delete.cshtml
@model Team8_MVCApplication.Models.CoreValueRecognitions

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CoreValueRecognitions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.personRecognized.profileFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.personRecognized.profileFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.personRecognizor.profileFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.personRecognizor.profileFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.award)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.award)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.recognizationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.recognizationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/CoreValueRecognitions/Details.cshtml
@model Team8_MVCApplication.Models.CoreValueRecognitions

@{
    ViewBag.Title = "Details";
}

<h2>Profile Details</h2>

<div>
    <h4>Full Detail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.personRecognized.fullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.personRecognized.fullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.personRecognizor.fullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.personRecognizor.fullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.award)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.award)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.recognizationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.recognizationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/CoreValueRecognitions/Edit.cshtml
@model Team8_MVCApplication.Models.CoreValueRecognitions

@{
    ViewBag.Title = "Edit";
}

<h2>Would you like to edit your profile?</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Make Edits Here.</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.recognized, "recognized", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("recognized", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.recognized, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.recognizor, "recognizor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("recognizor", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.recognizor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.award, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.award, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.award, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.recognizationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.recognizationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.recognizationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/CoreValueRecognitions/Index.cshtml
@model IEnumerable<Team8_MVCApplication.Models.CoreValueRecognitions>

@{
    ViewBag.Title = "Index";
}

<h2>Centric Profile Bank</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Employee Being Recognized
        </th>
        <th>
            Employee Giving the Recognition
        </th>
        <th>
            @Html.DisplayNameFor(model => model.award)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.recognizationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.personRecognized.fullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.personRecognizor.fullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.award)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.recognizationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comments)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

Views/CoreValueRecognitions/mailError.cshtml
@{
    ViewBag.Title = "mailError";
}

<h2>Mail Error</h2>

Google recently upgraded their security. Here is the message that would be sent to the user:
<br />
@TempData["mailError"].ToString();

@Html.ActionLink("Return to home", "index", "CoreValueRecognitions")