Models/Profile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Team8_MVCApplication.Models
{
    public class Profile
    {
        [Key]
        public Guid ProfileId { get; set; }

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Profile first name is required")]
        [StringLength(20)]
        public string profileFirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Profile last name is required")]
        [StringLength(50)]
        public string profileLastName { get; set; }

        [Required]
        [Display(Name = "Email Address")]
        [EmailAddress(ErrorMessage = "Enter your most used email address")]
        [StringLength(20)]
        public string email { get; set; }

        [Display(Name = "Business Unit")]
        public string businessUnit { get; set; }

        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^(\(\d{3}\) |\d{3}-)\d{3}-\d{4}$",
        ErrorMessage = "Phone numbers must be in the format (xxx) xxx-xxxx or xxx-xxx-xxxx")]
        public string phoneNumber { get; set; }

        [Display(Name = "Title")]
        public string title { get; set; }

        [Display(Name = "Hire Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime hireDate { get; set; }

        [Display(Name = "Employee Name")]
        public string fullName { get { return profileFirstName + ", " + profileLastName; } }


        [ForeignKey("recognizor")]
        public ICollection<CoreValueRecognitions> GivingtheRecognition { get; set; }

        [ForeignKey("recognized")]
        public ICollection<CoreValueRecognitions> BeingRecognized { get; set; }
    }
}

Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Team8_MVCApplication.DAL;
using Team8_MVCApplication.Models;
using PagedList;
using Microsoft.AspNet.Identity;

namespace Team8_MVCApplication.Controllers
{
    public class ProfilesController : Controller
    {
        private Team8_MVCApplication_Context db = new Team8_MVCApplication_Context();

        // GET: Profiles
        public ActionResult Index(string searchString)
        {

            var testProfile = from u in db.Profiles select u;

            if (!String.IsNullOrEmpty(searchString))
            {
                testProfile = testProfile.Where(u => u.profileLastName.Contains(searchString) || u.profileFirstName.Contains(searchString));
                // if here, users were found so view them
                return View(testProfile.ToList());
            }
            
            return View(db.Profiles.ToList());






        }

        // GET: Profiles/Details/5
        [Authorize]
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profile profile = db.Profiles.Find(id);
            if (profile == null)
            {
                return HttpNotFound();
            }
            return View(profile);
        }

        // GET: Profiles/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Profiles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProfileId,profileFirstName,profileLastName,email,businessUnit,phoneNumber,title,hireDate")] Profile profile)
        {
            if (ModelState.IsValid)
            {
                Guid memberId;
                Guid.TryParse(User.Identity.GetUserId(), out memberId);
                profile.ProfileId = memberId;
                db.Profiles.Add(profile);
                try
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {

                    return View("DuplicateUser");
                }

            }

            return View(profile);
        }

        // GET: Profiles/Edit/5
        [Authorize]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profile profile = db.Profiles.Find(id);
            if (profile == null)
            {
                return HttpNotFound();
            }
            Guid memberID;
            Guid.TryParse(User.Identity.GetUserId(), out memberID);
            if (profile.ProfileId == memberID)
            {
                return View(profile);
            }
            else
            {
                return View("NotAuthenticated");
            }
        }

        // POST: Profiles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProfileId,profileFirstName,profileLastName,email,businessUnit,phoneNumber,title,hireDate")] Profile profile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(profile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(profile);
        }

        // GET: Profiles/Delete/5
        [Authorize]
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profile profile = db.Profiles.Find(id);
            if (profile == null)
            {
                return HttpNotFound();
            }
            Guid memberID;
            Guid.TryParse(User.Identity.GetUserId(), out memberID);
            if (profile.ProfileId == memberID)
            {
                return View(profile);
            }
            else
            {
                return View("NotAuthenticated");
            }
            
        }

        // POST: Profiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Profile profile = db.Profiles.Find(id);
            db.Profiles.Remove(profile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Profiles/Create.cshtml
@model Team8_MVCApplication.Models.Profile

@{
    ViewBag.Title = "Create";
}

<h2>Create a New Profile</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Profile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.profileFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.profileFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.profileFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.profileLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.profileLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.profileLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.businessUnit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.businessUnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.businessUnit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hireDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hireDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hireDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Profiles/Delete.cshtml
@model Team8_MVCApplication.Models.Profile

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Profile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.profileFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.profileFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.profileLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.profileLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.businessUnit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.businessUnit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hireDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hireDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Profiles/Details.cshtml
@model Team8_MVCApplication.Models.Profile

@{
    ViewBag.Title = "Details";
}

<h2>Profile Page</h2>

<div>
    <h4>Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.profileFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.profileFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.profileLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.profileLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.businessUnit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.businessUnit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hireDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hireDate)
        </dd>

    </dl>
</div>

@{
    var id = Model.ProfileId;
    Team8_MVCApplication.DAL.Team8_MVCApplication_Context db = new Team8_MVCApplication.DAL.Team8_MVCApplication_Context();
    var recognition = db.CoreValueRecognitions.Where(p => p.personRecognized.ProfileId == id);
}



@{
    var Recognition = Model.BeingRecognized;
    var totalCnt = recognition.Count(); // counts all the recognitions for that person
    var excellentCnt = recognition.Where(r => r.award == Team8_MVCApplication.Models.CoreValueRecognitions.CoreValue.Excellence).Count();
    var excellentRec = recognition.Where(r => r.award == Team8_MVCApplication.Models.CoreValueRecognitions.CoreValue.Excellence);
    var balanceCnt = recognition.Where(r => r.award == Team8_MVCApplication.Models.CoreValueRecognitions.CoreValue.Balance).Count();
    var balanceRec = recognition.Where(r => r.award == Team8_MVCApplication.Models.CoreValueRecognitions.CoreValue.Balance);
    var innovativeCnt = recognition.Where(r => r.award == Team8_MVCApplication.Models.CoreValueRecognitions.CoreValue.Innovative).Count();
    var innovativeRec = recognition.Where(r => r.award == Team8_MVCApplication.Models.CoreValueRecognitions.CoreValue.Innovative);
    var acceptingCnt = recognition.Where(r => r.award == Team8_MVCApplication.Models.CoreValueRecognitions.CoreValue.Accepting).Count();
    var acceptingRec = recognition.Where(r => r.award == Team8_MVCApplication.Models.CoreValueRecognitions.CoreValue.Accepting);
    var integrityCnt = recognition.Where(r => r.award == Team8_MVCApplication.Models.CoreValueRecognitions.CoreValue.Integrity).Count();
    var integrityRec = recognition.Where(r => r.award == Team8_MVCApplication.Models.CoreValueRecognitions.CoreValue.Integrity);
    var passionCnt = recognition.Where(r => r.award == Team8_MVCApplication.Models.CoreValueRecognitions.CoreValue.Passion).Count();
    var passionRec = recognition.Where(r => r.award == Team8_MVCApplication.Models.CoreValueRecognitions.CoreValue.Passion);
    var stewardshipCnt = recognition.Where(r => r.award == Team8_MVCApplication.Models.CoreValueRecognitions.CoreValue.Stewardship).Count();
    var stewardshipRec = recognition.Where(r => r.award == Team8_MVCApplication.Models.CoreValueRecognitions.CoreValue.Stewardship);
}


<div class="container">
    <h2>Recognition Details</h2>
    <p>The table shows the combined awards given:</p>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Recognition</th>
                <th># of Awards</th>
                <th>Information about the Recognition</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Balance Awards</td>
                <td>@balanceCnt</td>
                <td>
                    @{
                        if (balanceCnt > 0)
                        {
                            <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">Details</button>
                            <div id="demo" class="collapse">
                                @Html.Partial("_coreValues", balanceRec)
                            </div>
                        }
                    }

                </td>
            </tr>
            <tr>
                <td>Culture Awards</td>
                <td>@acceptingCnt</td>
                <td>
                    @{
                        if (acceptingCnt > 0)
                        {
                            <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo1">Details</button>
                            <div id="demo1" class="collapse">
                                @Html.Partial("_coreValues", acceptingRec)
                            </div>
                        }
                    }

                </td>
            </tr>
            <tr>
                <td>Excellence Awards</td>
                <td>@excellentCnt</td>
                <td>
                    @{
                        if (excellentCnt > 0)
                        {
                            <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo2">Details</button>
                            <div id="demo2" class="collapse">
                                @Html.Partial("_coreValues", excellentRec)
                            </div>
                        }
                    }

                </td>
            </tr>

            <tr>
                <td>Innovative Awards</td>
                <td>@innovativeCnt</td>
                <td>
                    @{
                        if (innovativeCnt > 0)
                        {
                            <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo3">Details</button>
                            <div id="demo3" class="collapse">
                                @Html.Partial("_coreValues", innovativeRec)
                            </div>
                        }
                    }

                </td>
            </tr>

            <tr>
                <td>Integrity Awards</td>
                <td>@integrityCnt</td>
                <td>
                    @{
                        if (integrityCnt > 0)
                        {
                            <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo4">Details</button>
                            <div id="demo4" class="collapse">
                                @Html.Partial("_coreValues", integrityRec)
                            </div>
                        }
                    }

                </td>
            </tr>
            <tr>
                <td>Passion Awards</td>
                <td>@passionCnt</td>
                <td>
                    @{
                        if (passionCnt > 0)
                        {
                            <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo5">Details</button>
                            <div id="demo5" class="collapse">
                                @Html.Partial("_coreValues", passionRec)
                            </div>
                        }
                    }

                </td>
            </tr>
            <tr>
                <td>Stewardship Awards</td>
                <td>@stewardshipCnt</td>
                <td>
                    @{
                        if (stewardshipCnt > 0)
                        {
                            <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo6">Details</button>
                            <div id="demo6" class="collapse">
                                @Html.Partial("_coreValues", stewardshipRec)
                            </div>
                        }
                    }

                </td>
            </tr>
        </tbody>
        <thead>
            <tr>
                <th>Total Recognitions</th>
                <th>@totalCnt</th>
            </tr>
        </thead>
    </table>
</div>






@*<h2>Total recognitions received = @totalCnt</h2>
    <h3>Excellence awards = @excellentCnt</h3>
    <h3>Balance awards = @balanceCnt</h3>
    <h3>Integrity awards = @integrityCnt</h3>
    <h3>Culture awards = @acceptingCnt</h3>
    <h3>Passion awards = @passionCnt</h3>
    <h3>Stewardship awards = @stewardshipCnt</h3>
    <h3>innovative awards = @innovativeCnt</h3>*@










<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProfileId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Profiles/DuplicateUser.cshtml
@{
    ViewBag.Title = "DuplicateUser";
}

<br />
<br />
<div class="alert alert-danger">
    <h2>Not Allowed</h2>
    That user already exists - request not saved
</div>
<br />
@Html.ActionLink("Return to home", "index", "home")

Views/Profiles/Edit.cshtml
@model Team8_MVCApplication.Models.Profile

@{
    ViewBag.Title = "Edit";
}

<h2>Would you like to edit your profile?</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit Profile Below</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProfileId)

        <div class="form-group">
            @Html.LabelFor(model => model.profileFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.profileFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.profileFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.profileLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.profileLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.profileLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.businessUnit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.businessUnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.businessUnit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hireDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hireDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hireDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Profiles/Index.cshtml
@model IEnumerable<Team8_MVCApplication.Models.Profile>

@{
    ViewBag.Title = "Index";
}

<h2>Centric Profile Bank</h2>

<div class="form-horizontal">
    <div class="form-group">
        <div class="col-md-9">
            @using (Html.BeginForm("Index", "Profiles", FormMethod.Get))
            {
                <p>
                    Search for users by first or last name:
                    @Html.TextBox("searchString")
                    <input type="submit" value="Search" />
                </p>
            }
        </div>
        @*<div class="col-md-3">
            @Html.ActionLink("Create New", "Create")
        </div>*@
    </div>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.profileFirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.profileLastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.businessUnit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.hireDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.profileFirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.profileLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.businessUnit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.hireDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ProfileId }) |
                @Html.ActionLink("Details", "Details", new { id = item.ProfileId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ProfileId })
            </td>
        </tr>
    }

</table>

Views/Profiles/NotAuthenticated.cshtml
@{
    ViewBag.Title = "NotAuthenticated";
}
<br />
<br />
<div class="alert alert-danger">
    <h2>Not Allowed</h2>
    You are only able to edit your own profile.
</div>
<br />
@Html.ActionLink("Return to home", "index", "Profiles")

Views/Profiles/_coreValues.cshtml
@model IEnumerable<Team8_MVCApplication.Models.CoreValueRecognitions>


<table class="table">
    <tr>
        <th>
            Recognized By
        </th>
        <th>
            @Html.DisplayNameFor(model => model.personRecognizor.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.recognizationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>

    </tr>

@foreach (var item in Model)
{
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.personRecognizor.fullName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.personRecognizor.email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.recognizationDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Comments)
    </td>

</tr>
}

</table>